//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//

// AZ3166 platform configuration for WICED SDK.
// Normally generated by the WICED build system per-platform.
// Since ChibiOS manages clocks and peripherals, we only define
// the WiFi-related constants here.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// --------------------------------------------------------------------------
// Wi-Fi Options
// --------------------------------------------------------------------------

// GPIO pins are used to bootstrap Wi-Fi to SDIO mode
#define WICED_WIFI_USE_GPIO_FOR_BOOTSTRAP_0
#define WICED_WIFI_USE_GPIO_FOR_BOOTSTRAP_1

// Wi-Fi GPIO0 pin is used for out-of-band interrupt
#define WICED_WIFI_OOB_IRQ_GPIO_PIN (0)

// Wi-Fi power pin is present (active-high enable)
#define WICED_USE_WIFI_POWER_PIN

// Wi-Fi reset pin is present
#define WICED_USE_WIFI_RESET_PIN

// Use WLAN 32K internal oscillator
// (AZ3166 does not route MCO to the WiFi module)

// Firmware is embedded, not on filesystem
#ifndef WWD_DIRECT_RESOURCES
#define WWD_DIRECT_RESOURCES
#endif

// STM32F4 voltage range (2.7 – 3.6 V)
#define PLATFORM_STM32_VOLTAGE_2V7_TO_3V6

#ifdef __cplusplus
} // extern "C"
#endif
