//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "Com_SkyworksInc_NanoFramework_Devices_C1.h"
#include "Com_SkyworksInc_NanoFramework_Devices_C1_Com_SkyworksInc_NanoFramework_Devices_C1_C1Bus.h"

using namespace Com_SkyworksInc_NanoFramework_Devices_C1::Com_SkyworksInc_NanoFramework_Devices_C1;


HRESULT Library_Com_SkyworksInc_NanoFramework_Devices_C1_Com_SkyworksInc_NanoFramework_Devices_C1_C1Bus::NativeTransmitWrite___SZARRAY_U1__U1__U1( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        uint8_t param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 1, param0 ) );

        uint8_t param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 2, param1 ) );

        CLR_RT_TypedArray_UINT8 retValue = C1Bus::NativeTransmitWrite( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_UINT8_ARRAY( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_Com_SkyworksInc_NanoFramework_Devices_C1_Com_SkyworksInc_NanoFramework_Devices_C1_C1Bus::NativeTransmitRead___SZARRAY_U1__U1( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        uint8_t param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 1, param0 ) );

        CLR_RT_TypedArray_UINT8 retValue = C1Bus::NativeTransmitRead( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_UINT8_ARRAY( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}
