//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "Com_SkyworksInc_NanoFramework_Devices_C1.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_Com_SkyworksInc_NanoFramework_Devices_C1_Com_SkyworksInc_NanoFramework_Devices_C1_C1Bus::NativeTransmitWrite___VOID__U1__U1__SZARRAY_U1,
    Library_Com_SkyworksInc_NanoFramework_Devices_C1_Com_SkyworksInc_NanoFramework_Devices_C1_C1Bus::NativeTransmitRead___VOID__U1__SZARRAY_U1,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Com_SkyworksInc_NanoFramework_Devices_C1 =
{
    "Com.SkyworksInc.NanoFramework.Devices.C1",
    0x89A74791,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
